// pages/about/about.js
Page({
  data:{
      content:{
          title:'河南手机报远程发稿系统小程序版使用指南',
          content:[
              {
                  type:'text',
                  value:"提示：教程为手机录屏及解说，流量不充足请在wifi下观看，全部视频总计大小约为500MB"
              },
              {
                  type:'text',
                  value:"1.首次进入小程序"
              },
              {
                  type:'video',
                  value:"https://www.hnsjb.cn/video/weapp-guide/enter.mp4"
              },
              {
                  type:'text',
                  value:"2.进入小程序"
              },
              {
                  type:'video',
                  value:"https://www.hnsjb.cn/video/weapp-guide/reenter.mp4"
              },
              {
                  type:'text',
                  value:"3.记者发稿"
              },
              {
                  type:'video',
                  value:"https://www.hnsjb.cn/video/weapp-guide/reporter.mp4"
              },
              {
                  type:'text',
                  value:"4.编辑稿件"
              },
              {
                  type:'video',
                  value:"https://www.hnsjb.cn/video/weapp-guide/edit.mp4"
              },
              {
                  type:'text',
                  value:"5.复制内容到文章正文"
              },
              {
                  type:'video',
                  value:"https://www.hnsjb.cn/video/weapp-guide/paste.mp4"
              },
              {
                  type:'text',
                  value:"6.删除图片或视频"
              },
              {
                  type:'video',
                  value:"https://www.hnsjb.cn/video/weapp-guide/delete-img.mp4"
              },
              {
                  type:'text',
                  value:"7.删除稿件"
              },
              {
                  type:'video',
                  value:"https://www.hnsjb.cn/video/weapp-guide/delete-post.mp4"
              },
              {
                  type:'text',
                  value:"8.驳回稿件"
              },
              {
                  type:'video',
                  value:"https://www.hnsjb.cn/video/weapp-guide/reject.mp4"
              },
              {
                  type:'text',
                  value:"9.通过稿件"
              },
              {
                  type:'video',
                  value:"https://www.hnsjb.cn/video/weapp-guide/pass.mp4"
              },
              {
                  type:'text',
                  value:"10.转审稿件"
              },
              {
                  type:'video',
                  value:"https://www.hnsjb.cn/video/weapp-guide/forward.mp4"
              },
              {
                  type:'text',
                  value:"11.列表页说明"
              },
              {
                  type:'video',
                  value:"https://www.hnsjb.cn/video/weapp-guide/list.mp4"
              },
              {
                  type:'text',
                  value:"12.修改密码"
              },
              {
                  type:'video',
                  value:"https://www.hnsjb.cn/video/weapp-guide/resetpassword.mp4"
              }
          ],
          inputtime:'2017-03-13',
          username:'产品支撑部',
          copyright:'version 0.8.4'
      }
  },
  onLoad:function(options){
    // 页面初始化 options为页面跳转所带来的参数
  },
  onReady:function(){
    // 页面渲染完成
  },
  onShow:function(){
    // 页面显示
  },
  onHide:function(){
    // 页面隐藏
  },
  onUnload:function(){
    // 页面关闭
  }
});